### ISSUE TITLE
Stop redirect on local login

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback-component-passport#100]
I want to be able to use the local login endpoint using CORS with preflight. 3xx redirects are disallowed with preflight, but there is no way to disable redirect properly.

You can set the options.fn for the local provider, but then you do not have the Express result object in scope!

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by gausie** [comment]
I'm not able to do that just yet. I have just moved away form passport-local, using /api/users/login instead.

**Comment by ataft** [comment]
Has anyone figured out an easy way to do this? It seems that @gausie moved away from loopback passport in favor of /api/users/login. Others (as per [this ](https://gitter.im/strongloop/loopback?at=55074cdd67cfef4f51e2345e)gitter) moved away from loopback passport to just using passport directly. 

I like the idea of using loopback's passport module, so hopefully this can be addressed. As per the gitter post above (and my thoughts too), it appears the issue is that PassportConfigurator needs to wrap the passport.authenticate() call in a request handler so we can pass in a callback that has access to req/res/next. In looking at [these ](https://github.com/strongloop/loopback-component-passport/blob/master/lib/passport-configurator.js#L561-L573)PassportConfigurator lines, the LDAP auth type does this, but the local auth type calls passport.authenticate directly. Changing the local logic to the following works for me:
```
var localCallback = options.customCallback || defaultCallback;
self.app.post(authPath, localCallback);

```

I would think that this should be done consistently for all the auth types (maybe not link). Is this something that's being worked on?
