### ISSUE TITLE
https in callback URL

### ISSUE THREAD

**Issue by sochka** [strongloop/loopback-component-passport#120]
Hi, if I have this relative callback in the config: `callbackURL: '/auth/google/callback'` and the website is accessed through HTTPS shouldn't loopback automatically resolve callbackURL to `https://DOMAIN_NAME/auth/google/callback`? I believe it should, but indeed, it resolves to http.

**Comment by JensWinter** [comment]
I'm also wondering about this...

**Comment by sochka** [comment]
@raymondfeng, any feedback on this? I don't know how to resolve this problem without using absolute URI which would make my website available only on one domain/protocol.

**Comment by jannyHou** [comment]
@sochka I am trying to debug this problem, could you upload your code in this [sandbox](https://github.com/strongloop/loopback-sandbox)?
When I login facebook account, I just use `"callbackURL": "/auth/facebook/callback",` and facebook is using `https`, so I am a little confused.
Thanks.

**Comment by clockworkgr** [comment]
the relevant code is part of passport-oauth2. passport-facebook inherits from that

in passport-oauth2/lib/strategy.js line:140

```
var callbackURL = options.callbackURL || this._callbackURL;
  if (callbackURL) {
    var parsed = url.parse(callbackURL);
    if (!parsed.protocol) {
      // The callback URL is relative, resolve a fully qualified URL from the
      // URL of the originating request.
      callbackURL = url.resolve(utils.originalURL(req, { proxy: this._trustProxy }), callbackURL);
    }
  }
```

So if you redirect your users to http://ww.your-server.com/auth/facebook,

passport-oauth2  will create an http:// absolute URL for the callback

if you redirect them to https://ww.your-server.com/auth/facebook

then it will create an https:// one for the callback

Or at least that is the expected behaviour.

**Comment by jannyHou** [comment]
Thank you @clockworkgr I am looking into this issue.
@sochka  @JensWinter 
When my "website is accessed through HTTPS" it does has some problem, but I am not sure is it caused by exactly the same error you describe:
![https](https://cloud.githubusercontent.com/assets/12554153/14361904/2aa62230-fccb-11e5-832b-9523ef97fe3b.PNG)

Could any of you confirm this? thanks!

**Comment by clockworkgr** [comment]
@jannyHou That's a standard facebook app misconfiguration error

assuming you have your loopback app at myapp.com (so when logging in with facebook , facebook is told to redirect the user to myapp.com/auth/facebook/callback or whatever you've set your callback to)
then your facebook app should have myapp.com set as the app domain under Settings

Here's a screenshot
![image](https://cloud.githubusercontent.com/assets/6826762/14364986/1453ce26-fd14-11e5-96e8-bf2dab1f8f8e.png)
App Domains should have myapp.com under it

**Comment by tmarshall** [comment]
I'm experiencing the same. I dug into it, and it's coming from [the passport-oauth2 utils method](https://github.com/jaredhanson/passport-oauth2/blob/master/lib/utils.js#L29).

`proto` shows https, while `tls` is false. Boils down to the site being proxied (through a load balancer, etc) - and it is not trusting the proxy, causing it to fall back to http. 

The fix is to add `proxy: true` in the options passed to the strategy. This signals that it's a trusted proxy, and `tls` will switch to `true`. Just worked for me.
