### ISSUE TITLE
[v2.0.0] Local strategy: ER_BAD_FIELD_ERROR: Unknown column 'username' in 'where clause'

### ISSUE THREAD

**Issue by terusus** [strongloop/loopback-component-passport#122]
When the app is working with a MySQL data source the following error occurs when the user is set up to use only email and password. 

User model description:

``` json
"properties": {
  ...
  "username": false,
  ...
},
```

Providers description:

``` json
"local": {
  "provider": "local",
  "module": "passport-local",
  "usernameField": "email",
  "passwordField": "password",
  "authPath": "/auth/local",
  "successRedirect": "/",
  "failureRedirect": "/auth/local",
  "failureFlash": true
}
```

**Comment by jannyHou** [comment]
@terusus Could you post what errors are you getting?
I am trying to reproduce your question, and for a better debugging, please replace the [sandbox](https://github.com/strongloop/loopback-sandbox), or explain the steps to reproduce your problem:) thanks!

**Comment by clockworkgr** [comment]
just to help out:

Starting in passport-configurator.js line: 244
```

passport.use(name, new AuthStrategy(_.defaults({
          usernameField: options.usernameField || 'username',
          passwordField: options.passwordField || 'password',
          session: options.session, authInfo: true
        }, options),
        function(username, password, done) {
          var query = {
            where: {
              or: [
                {username: username},
                {email: username}
              ]
            }
          };
          self.userModel.findOne(query, function(err, user) {
```

the query above : "where username=username or email=username" is fine for mongodb but breaks on SQL. the relevant code should be changed to create a 

"where {options.usernameField}=username" 

query instead

**Comment by terusus** [comment]
This error means that the SQL database should have a field `username` for every user even if it is not used. This is just because the component creates the where query always with `email` and `username`.

Partial schema:
```
| Field         | Type         | Null | Key | Default | Extra          |
+---------------+--------------+------+-----+---------+----------------+
...
| username      | varchar(512) | YES  |     | NULL    |                |
| password      | varchar(512) | NO   |     | NULL    |                |
| email         | varchar(512) | NO   |     | NULL    |                |
...
```

PS: The error is the title of the post. SQL errors do not get more descriptive than that.

**Comment by jannyHou** [comment]
Thank you @clockworkgr @terusus your explanations are reasonable, but I have some problem when reproducing this error:
I am using https://github.com/strongloop/loopback-example-passport, and create a mysql datasource, then attach model `user` to it.
When I start the app, try to signup, I get error:
```
The `user` instance is not valid. Details: `email` is invalid (value: "aaa@gmail.com"); `username` is invalid (value: "aaaaa").
```
The same result when I set `"usernameField": "email",`
And I do have `username` in my mysql ds table.

Could any of you upload the code to sandbox I mentioned? 
https://github.com/strongloop/loopback-component-passport/issues/122#issuecomment-204565737
Thanks a lot.

And I think if you auto-migrate your model `user` to mysql, you will have `username` field in mysql, which should solve the problem according to your description(if no `username` column existed is the only reason causes error), because it extends the base model `User`, which has `username` field.

**Comment by clockworkgr** [comment]
Well the problem appears when the table does NOT have a username field (right @terusus ?)

I guess technically this is expected behaviour since user account models should extend User which has the username field but I can see why someone doesn't want to have it  if they're not using it.

**Comment by terusus** [comment]
1) Inherit the user model and make a property declaration with `"username": false`.
2) Create the MySQL database for your project. (You should not have a username field in your custom user table.)
3) Use the provider description json with:
```json
{
  ...
  "usernameField": "email",
  "passwordField": "password",
  ...
}
```
4) :boom:
