### ISSUE TITLE
Where does account security come from with social login?

### ISSUE THREAD

**Issue by jubbens** [strongloop/loopback-component-passport#127]
I have seen other people indicate that social logins should be authenticated using `UserIdentity.login()`. I see that I can allow people to pass in an `id` and an `accessToken` to that function and if a local `User` does not already exist for this social login, one will be created. Great!

However, it seems like now anybody who knows that `id` can use it to perform a social login with that account and gain access to that local user. They don't even have to pass in the same `accessToken` in order for `UserIdentity.login()` to grant them access to that local user. This seems like a huge security issue to me, especially since that `id` is not hashed in the database. 

Am I going about this wrong, or does loopback-component-passport expose this security hole by design?

**Comment by BerkeleyTrue** [comment]
I don't think `UserIdentity.login()` is exposed to the outside world

**Comment by jeff3yan** [comment]
I'm also unsure of the best practice of using UserIdentity.login(). The current passport strategy usage only uses the _redirect_ method of logging a user in.

For providers such as Auth0, they provide their own client-side widget, which can be styled and embedded directly onto the page. The jwt can then be decrypted on some public loopbackjs endpoint, then UserIdentity.login() called using their details.

However, the documentation for UserIdentity.login is a bit lacking and I'm unsure of how to exactly match various parameters so that the current passport-auth0 system can be used _as well_ as this custom endpoint - with the same results in the database.

**Comment by BerkeleyTrue** [comment]
UserIdentity.login does not need to be used directly. This module is meant to interface loopback and passport. You simply use the proper redirects for the 3rd party O-auths and this module takes care of the rest.

As far as the main issue here, UserIdentity.login is not exposed through the api and as so is not a security issue. This issue can be closed. @jannyHou

**Comment by jubbens** [comment]
Thanks @jeff3yan @BerkeleyTrue. I agree, this can be closed if login is not supposed to be used like this.

**Comment by BerkeleyTrue** [comment]
For reference, here are the relevant files that we use at FreeCodeCamp to make this work:

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/component-passport.js
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/passport-providers.js

And how we load it on server boot:

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/server.js#L10
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/server.js#L28

We also overwrite the login methods elsewhere but their signatures remain the same. So for the purposes of this issue they are irrelevant.

For anyone trying to use this module the first two links are what you need to get running.

I would also suggest to anyone starting a project that they stick to email and only ONE third party O-Auth provider or just email alone. We originally started with 4 and had/still have a huge headache when users forget which social login they used, create a new account without realizing it, and then they believe all their user data has been lost. 

We have since removed the ability to create new accounts with all but one social O-Auth and will eventual remove the ability to login with the old ones as well.

**Comment by jannyHou** [comment]
Thanks everyone! Really appreciate you discussion and reference provided!
