### ISSUE TITLE
Doc issues

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback-component-passport#148]
I tried to make use of this today, but I had to give up as it felt like a bit too much. To be fair, I've never used Passport before, so 99% of my problem probably stems from that. The docs (https://docs.strongloop.com/display/APIC/Third-party+login+using+Passport) talk about installation, and I thought that was literally it. (I mean outside of setting up a FB app, configuration, etc.) Obviously that isn't all you need to do. I tried copying code in from the sample app (I didn't want to take it as is - I had an existing app) and kept running into issues because of modules I didn't have yet. 

So I guess my take away here is - maybe the doc should start off by warning folks that they should have a basic understanding of Passport first?

Also, it seems to assume a lot. For example, "Configuration in providers.json" - I had no idea what this file was or where it belonged. (I see the path shown later in the code, but _after_ this section, and folks may just stop there.)

Also - we're supposed to add in  "./node_modules/loopback-component-passport/lib/models"  to model-config.json so we can pick up the models there. That's shown in the sample app but not the docs itself. 

I know I'm not doing a good job of writing up the issue and I apologize. I'm going to skip using this now and try to use Passport by itself w/ no LoopBack integration to see if being familiar with it more helps me out.

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Thanks for the input @cfjedimaster 

> maybe the doc should start off by warning folks that they should have a basic understanding of Passport first?

I added a note to this effect at the top of https://docs.strongloop.com/display/APIC/Third-party+login+using+Passport.

> ... "Configuration in providers.json" - I had no idea what this file was or where it belonged.  ..
I added a reference in that section to https://docs.strongloop.com/display/APIC/Configuring+providers.json which explains it a bit more.

> .. we're supposed to add in "./node_modules/loopback-component-passport/lib/models" to model-config.json so we can pick up the models there.

OK, that part I don't know about...  It's been well over a year since I messed with this component (and wrote this doc), so I may just be forgetting.  It looks like that's where it gets the UserIdentity, UserCredential, and ApplicationCredential models... but that seems like lame way to do it.  I can certainly add that info, but I'd like to explain why you have to do it that way.  Is this just because it's not a "real" component?  And is that really the "best practice" way to do it?

@superkhau Do you know?

**Comment by superkhau** [comment]
@crandmck I am not familiar enough with this module to answer. Let's get @raymondfeng or @bajtos's input here so you can update the docs with some minimal workaround. I'm not sure when the refactor will happen in our list of priorities TBH.

@jannyHou Can you link to that refactor issue that is related to this?

**Comment by crandmck** [comment]
I addressed the above comments in https://loopback.io/doc/en/lb3/Third-party-login-using-Passport.html
