### ISSUE TITLE
Support for extended User models

### ISSUE THREAD

**Issue by thovden** [strongloop/loopback-component-passport#49]
loopback-component-passport does not work with extended User models - i.e., 
`common/models/user.json`

``` json
{
  "name": "user",
  "plural": "users",
  "base": "User",
...
```

This is due to hardcoded references to User in `user-credential.json` and `user-identity.json` models - i.e., 

``` json
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    }
```

**Comment by clockworkgr** [comment]
The problem is not so much in the model definitions as such since you could easily handle that by extending UserCredential and UserIdentity as well and overriding the relations to end up with your own Customer, CustomerIdentity, CustomerCredential for example.

This refers to the js model files as well as the json files since they are littered with hardcoded references,

So if you wanted the relation above to refer to a different (extended) User model with a different foreign key you would have to redefine the user relation in an extended Identity model with a different foreignKey and switch all the userId references in your Identity's js file.

Inefficient & Ugly but it is not the real problem so far. You could make sure that all your foreignKeys are the same as the original ones to not have to do that. Right?

Wrong!

The real problem is that loopback handles non-specified parameters to  hasMany and belongsTo relations differently.

From the docs:

hasMany: 
Foreign key: The camel case of the declaring model name appended with ‘Id’, for example, for model name "Customer" the foreign key is "customerId".

belongsTo:
Foreign key: The relation name appended with ‘Id’, for example, for relation name "customer" the default foreign key is "customerId".

This becomes a problem in PassportConfigurator.setupModels() where we have:
```
  if (!this.userModel.relations.identities) {
    this.userModel.hasMany(this.userIdentityModel, {as: 'identities'});
  } else {
    this.userIdentityModel = this.userModel.relations.identities.modelTo;
  }
  if (!this.userModel.relations.credentials) {
    this.userModel.hasMany(this.userCredentialModel, {as: 'credentials'});
  } else {
    this.userCredentialModel = this.userModel.relations.credentials.modelTo;
  }
```

Since loopback-component-passport does not define its own User model, we have to make sure that whatever our extended User model is, already contains the identities and credentials relations because the code above will lead to the foreignKeys for the two relations above to be {customUser}Id which obviously is not referenced anywhere in Identity and Credential models.

I stumbled upon this as well and I'm in the process of writing a patch to ensure that all references derive from the extended User Model name.

**Comment by clockworkgr** [comment]
https://github.com/strongloop/loopback-component-passport/pull/93

**Comment by jubbens** [comment]
@clockworkgr Any progress towards this? This seems like an absolutely colossal bug since the [Loopback docs](https://docs.strongloop.com/display/public/LB/Using+built-in+models#Usingbuilt-inmodels-Usermodel) state

> You must create your own custom model (named something other than "User," for example "Customer" or "Client") that extends the built-in User model rather than use the built-in User model directly.  The built-in User model provides a great deal of commonly-used functionality that you can use via your custom model.

**Comment by clockworkgr** [comment]
@jubbens I've referenced my initial fix PR in the comment above...

Since then @jonathan-cassarubias has published a more polished version of the fix which is referenced here:https://github.com/strongloop/loopback-component-passport/pull/93#issuecomment-156843885

Really have no idea why this hasn't been merged yet :/

**Comment by mediapolis** [comment]
+1

**Comment by wprater** [comment]
thanks to work above, I created a new branch based off latest `2.1.0`.

**Comment by wprater** [comment]
looks like this was never resolved?
