### ISSUE TITLE
accessToken cookie not being set for local-login

### ISSUE THREAD

**Issue by Gouthamve** [strongloop/loopback-component-passport#57]
I was trying to use make an authenticated api call after logging in using the passport-local. But the accessToken signed cookie is not being set for local.

When I login through Fb, I get a signed cookie with accessToken but that is not happening for local. I have added the following option to providers.json for local but still the cookie is not being set.

``` json
"setAccessToken": true
```

Steps to reproduce:
Clone the `loopback-example-passport` repo and use the local login. You will see that the accessToken is virtually impossible to retrieve.

**Comment by JulienCabanes** [comment]
Same problem here :(

**Comment by JulienCabanes** [comment]
I figured out what's going wrong and how to get around:
- Local auth does generate an accessToken but it doesn't set the cookies accordingly as it does with facebook auth. The workaround is to get the last accessToken and set the cookies by hand inside the success callback.
```
res.cookie('access_token', accessToken.id, {
  signed: req.signedCookies ? true : false,
  maxAge: 1000 * accessToken.ttl
});
res.cookie('userId', user.id.toString(), {
  signed: req.signedCookies ? true : false,
  maxAge: 1000 * accessToken.ttl
});
```
- There's also an issue with the local signup where `req.login()` does not generate any accessToken at all, the workaround is to use `User.login()` after it...

**Comment by bryannaegele** [comment]
Thank you, thank you @JulienCabanes. This was driving me insane.

I added the following to a boot script as a modification to user. 

```
'use strict';

module.exports = function(app) {
  app.models.user.afterRemote('login', function(context, accessToken, next) {
    let res = context.res;
    let req = context.req;

    if (accessToken != null) {
      if (accessToken.id != null) {
        res.cookie('access_token', accessToken.id, {
          signed: req.signedCookies ? true : false,
          maxAge: 1000 * accessToken.ttl
        });
        res.cookie('userId', accessToken.userId.toString(), {
          signed: req.signedCookies ? true : false,
          maxAge: 1000 * accessToken.ttl
        });
      }
    }
    return next();
  });

  app.models.user.afterRemote('logout', function(context, result, next) {
    let res = context.result;
    res.clearCookie('access_token');
    res.clearCookie('userId');
    return next();
  });
};
```

**Comment by adnanshatil** [comment]
It works fine for me during login ... but not in logout

This is because __app.models.user.afterRemote__ method's callback function ... 
__context.result__ always returns null. as a result __res.clearCookie__ fails. 

How can I solve this?

**Comment by gausie** [comment]
I am currently not using sessions and would ideally like the accessToken to be appended to the success callback route in some way (in req.authInfo for example). Is that possible?

**Comment by superkhau** [comment]
@bajtos @raymondfeng @ritch I'm not sure about this one, PTAL.

**Comment by jamesjjk** [comment]
+1 local login is not setting cookie for accesstoken or returning token req.accessToken. Does not allow for local-login to be used.

**Comment by PhuongNL** [comment]
Same problem, i dont know how to get access token when use passport local.

**Comment by PhuongNL** [comment]
I found the solution, **install cookie-parser**, add this line to server.js: **app.middleware('session:before', loopback.cookieParser(app.get('cookieSecret')));**.
 after **successRedirect** to **"/auth/account"**, in this router u can get accesstoken by **req.cookies.accessToken**.

**Comment by jamesjjk** [comment]
@PhuongNL but the cookie is not set client side. There is a problem with the callback for passport local

**Comment by PhuongNL** [comment]
@jamesjjk yes, we need other solution.

**Comment by gshireesh** [comment]
i added the following change and it is working for me now.

https://github.com/strongloop/loopback-component-passport/compare/master...gshireesh:master

then add <code>"forceDefaultcallback" : true </code> to the  providers.json

the logout code will be 
```node
app.get('/auth/logout', ensureLoggedIn('/login'), function (req, res, next) {
  req.logout();
  var accessToken  = req.accessToken || "";
  if(accessToken){
    console.log('found access tocken', accessToken);
    var User = app.models.User;
    User.logout(accessToken, function (err) {
      console.log(err || 'Logged out');
    });
  }
  else{
    console.log("unable to find the access token");
  }
  res.redirect('/');
});
```

Hope it works for you too  :)

**Comment by jamesjjk** [comment]
@gshireesh I have implemented your fix from the PR, however req.accessToken still returns a null object for local passport. Also I see no reference to forceDefaultCallback in the code? Any ideas of what it could be

**Comment by jamesjjk** [comment]
@gshireesh Thank you for your solution but there is an error in your solution. On line 470 : info.accessToken.ttl (see comment). Also you have changed an earlier PR I noticed from (line 307):
    userProfile.accessToken = accessToken;
    done(null, user, {accessToken: accessToken});

from

    userProfile.accessToken = accessToken;
    done(null, userProfile, {accessToken: accessToken});

Why if I may ask?

**Comment by jamesjjk** [comment]
I have an updated forked version here which also supports Email verification on the defaultCallback for those looking for that option. It requires the attribute "emailVerificationRequired" : true in your respective providers.json. https://github.com/jamesjjk/loopback-component-passport

**Comment by gustavomick** [comment]
trying to understand here.. why do we need two tokens stored in two diferent places? .. thanks!

**Comment by e97** [comment]
@jamesjjk thank you, works for me.

**Comment by jamesjjk** [comment]
@gustavomick can you expand?

**Comment by gustavomick** [comment]
@jamesjjk 
1) i used both original and your solution but req.accessToken is still undefined after redirect (using setAccessToken:true). its ok to say that would be filled as facebook strategy? (req.user is filled)
2 ) how do i read (after redirect) info accessToken filled on passport-configurator.
thanks

**Comment by gustavomick** [comment]
@jamesjjk okay after bbt2 .. i noticed that options.cookie must be true on yours, why isn't default option? thanks.

**Comment by julien-sarazin** [comment]
Any pull request validated for this issue?

**Comment by jamesjjk** [comment]
@gustavomick Its simply a fix that @gshireesh kindly implemented, and I had done a similar job prior and decided to extend, yes it should be a default option - feel free to implement. We are just community members implementing a solution for these issues.

**Comment by julien-sarazin** [comment]
@jamesjjk Thanks a lot. I don't want to be pushy but is there any pending PR?

**Comment by jamesjjk** [comment]
@julien-sarazin I'm not part of the LB team and I don't have PR rights. Its good to share back with the community. Feel free to request from @superkhau @raymondfeng. Else use my repo as a source "loopback-component-passport": "git+https://github.com/jamesjjk/loopback-component-passport.git"

**Comment by tiagolr** [comment]
Thank you @bryannaegele your solution works really well.

**Comment by dineshi2it** [comment]
@bryannaegele  @tiagolr  I just copied those code and pasted it under boot directory by saving it as set-remove-cookie.js. But it is not working. Am I doing anything wrong or missing something?

**Comment by tiagolr** [comment]
Well i place it pretty much at the end of boot scripts, after the following middleware:
```
  app.use(loopback.context());
  app.use(loopback.token());
  app.disable('x-powered-by');
```

**Comment by tiagolr** [comment]
I actually moved those remote hooks to inside `users.js` file.

Try using the `loopback.context()` and `loopback.token()` middleware, see if it that is what's causing the problem.

**Comment by dineshi2it** [comment]
I added `app.use(loopback.context());` above 
```
app.middleware('auth', loopback.token({
  model: app.models.accessToken
}));
```
and my `common/model/user.js` looks

```
module.exports = function(user) {
	user.afterRemote('logout', function(context, result, next) {
	  console.log("====checking=======");
	  var res = context.result;
	  res.clearCookie('access_token');
	  res.clearCookie('userId');
	  return next();
	});
};
```

and in `server/server.js` I have this

```
//this part works fine  
app.get('/auth/logout', function (req, res, next) {
  req.logout();
  res.redirect('/');
});
```

still remote hook doesn't work.

**Comment by tiagolr** [comment]
Does the console log anything? I'm using default 'users/api/login' and '/api/users/logout' here. What is the error?

**Comment by RAJESHI2IT** [comment]
@tiagolr I didn't use api login and just learnt why remote hook is actually for. Thanks a lot.

**Comment by RAJESHI2IT** [comment]
@tiagolr I had the same problem and I didn't use api login and just learnt why remote hook is actually for. Thanks a lot.

**Comment by dineshi2it** [comment]
@tiagolr @RAJESHI2IT Thanks. That was the problem. It is works great if I use API login.

**Comment by jmwohl** [comment]
@dineshi2it Sounds like you sorted things out, but regarding this:

```
module.exports = function(user) {
    user.afterRemote('logout', function(context, result, next) {
      console.log("====checking=======");
      var res = context.result;
      res.clearCookie('access_token');
      res.clearCookie('userId');
      return next();
    });
};
```

The line `var res = context.result;` should read `var res = context.res;`. If you're using the example provided way up there by @bryannaegele, that's the issue... after that change, logging out via the API will also clear the cookies.

**Comment by bryannaegele** [comment]
@jmwohl Good catch. I updated the example.

**Comment by yanalavishnu** [comment]
Based on the code local config should be done like this
```
"local": {
  "provider": "local",
  "module": "passport-local",
  "usernameField": "username",
  "passwordField": "password",
  "authPath": "/api/users/login",
  "callbackPath": "/api/users/login",
  "failureRedirect": "/local",
  "setAccessToken": true,
  "session" : true,
  "callbackHTTPMethod": "post"
}
```

**Comment by elropero** [comment]
I've spent the last few days banging my head against this issue. I think it all just clicked for me, but wanted to recap for newcomers. 

1) The `afterRemote('login')` solution will only work if you adjust your providers.json to use `/api/users/login` (as opposed to the sample which uses `/auth/local`). When you use `/auth/local` the *remote hook will NOT trigger* (because you are not calling a remote method on the `users` model). 

For this solution, to remove the cookies on logout you could theoretically make sure to call directly to `/api/users/logout` and pass access_token, though when I POST to that route and pass a valid `access_token` I get a "could not find accessToken" error. So, I've left the `GET /auth/logout` route in place from the example and added the following cookie cleanup code:

```
app.get('/auth/logout', function (req, res, next) {
    if (!req.accessToken) return res.sendStatus(401); //return 401:unauthorized if accessToken is not present
    app.models.person.logout(req.accessToken.id, function(err) {
      if (err) return next(err);
      // Clear the session cookies
      res.clearCookie('access_token');
      res.clearCookie('userId');
      res.redirect('/'); //on successful logout, redirect
    });
});
```

2) Alternatively, you can use the solution collaborated on by @jamesjjk and @julien-sarazin -- which lets you keep the sample `providers.json` in place and will set the `access_token` cookie for you as part of the response (from within our beloved `passport-configurator.js`). There are a few variations on this theme but this commit from @jamesjjk's repo seems best:
https://github.com/jamesjjk/loopback-component-passport/commit/3b3f147c19e31a22ffedafbbcfef6232a9aee854
* Bear in mind that for this solution you still have to manually remove the cookies -- you can use the same solution as above. 

I feel either of these solutions is suboptimal, but at least here's something workable. Hope this saves the next person to arrive at this thread a couple of days.

**Comment by shuhankuang** [comment]
How can I get the auth-local work example, Now I can't get the accountToken from req.* .

**Comment by hackerunet** [comment]
I got to the same conclusion after 2 days hitting against my laptop. If I don't have any remote hook called /auth/local how can this work?, I supposed passport-local strategy automatically posted the remote hook via providers.json which I think it does it. but I'm not very sure about it, so, I can see there are still problems with this component, so would be easier to use passport alone as it's supposed to be used normally with express? And maybe keep 2 authentication models, the passport based and the accesstoken based.
What do you think?, Also when I use "setAccessToken": true, I get nothing but an Unauthorized message when I attempt to login and of course an already sent headers error but in the database (mongodb) I can see my user token created and store, and when I remove setAccessToken:true from providers.json I don't see anything in the database and no error displayed.
What's the fix for this issue?

**Comment by hackerunet** [comment]
I found the way to get passport installed and running using passport plugin as standalone and removed loopback-passport-component , basically I got express session object access and serialize the token received after req.login procedure which is the standard loopback procedure to control access to the API.
So, due to the loopback component existent issues and the relatively differences between docs and examples I think I took the best choice in order to advance on this and solve the session persistency and MVC pattern support. if anyone can debate on this, is totally welcome so maybe we could improve the solution.

**Comment by hackerunet** [comment]
Finally this issue is totally solved using this issue: https://github.com/strongloop/loopback-component-passport/issues/57
"loopback-component-passport": "git+https://github.com/jamesjjk/loopback-component-passport.git"
No more headaches.. thanks a lot @julien-sarazin , have spent so many hours looking around for solutions, I learned a lot, but you did it.. thanks a lot man...!!

**Comment by hackerunet** [comment]
I'm sorry to insist on this, but I have a question to @julien-sarazin, the access_token stored in the cookies is hashed. How can I use it? should I decript/dehashed the access_token first before sending the requests to my api server? or should I just send it like it is (hashed) and loopback will dehash the access_token for me? any docs about it?

**Comment by hackerunet** [comment]
Dear group, I'm still facing issues with this passport aproach even with the  @julien-sarazin repository, after I successfully login I enabled the security debug mode to see why I get DENY response in every request made to the API.
The login works and I see in the browser cookies 
access_token: ""s:Qte2qXpncpqe9vi9LduF78FjjMiCFrIGXGVBV4Uh8a1IelylFtgFdQj1xmKrFNGG.elA1qIs/QmUvaFYhx+lvn6jocYcPzQU2HOrsWUVAk1M""
and also connect.sid and userId all signed or crypted.
So I added 4 custom roles and test the ACL access using the API explorer directly and I successfully got access to all granted methods.
In the application ater I login and get redirected to the privated area and all cookies are available in the browser I sent an API request and this is what I got:
```
loopback:security:access-context accessType READ +1ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "$anonymous" +1ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context getUserId() null +1ms
  loopback:security:access-context isAuthenticated() false +0ms
```
Clearly the cookies and the repository are not doing anything at all over the API but passport granted access on LOGIN and successfully redirected to the private are.
So my concern here is how can I have this working ???? so, also in my request headers I see:
```
X-Access-Token: s:Qte2qXpncpqe9vi9LduF78FjjMiCFrIGXGVBV4Uh8a1IelylFtgFdQj1xmKrFNGG.elA1qIs/QmUvaFYhx+lvn6jocYcPzQU2HOrsWUVAk1M
```
So what's left to check is my server.js configuration:
```
'use strict';

var loopback = require('loopback');
var boot = require('loopback-boot');
var app = module.exports = loopback();
var bodyParser = require('body-parser');
var cookieParser = require('cookie-parser');
var session = require('express-session');
var flash = require('express-flash');
var secret = require('../config/secret.json').cookieSecret;

// Passport configurators..
var loopbackPassport = require('loopback-component-passport');
var PassportConfigurator = loopbackPassport.PassportConfigurator;
var passportConfigurator = new PassportConfigurator(app);

// attempt to build the providers/passport config
var config = {};
try {
  config = require('../config/passport.json');
} catch (err) {
  console.trace(err);
  process.exit(1); // fatal
}

// to support JSON-encoded bodies
app.middleware('parse', bodyParser.json());
// to support URL-encoded bodies
app.middleware('parse', bodyParser.urlencoded({
  extended: true,
}));

// The access token is only available after boot
app.middleware('auth', loopback.token({
  model: app.models.AccessToken
}));

app.middleware('session:before', cookieParser('secret'));
app.middleware('session', session({
  secret: 'secret',
  saveUninitialized: true,
  resave: true
}));
passportConfigurator.init();

boot(app, __dirname);

// We need flash messages to see passport errors
app.use(flash());

passportConfigurator.setupModels({
  userModel: app.models.sentinel_account,
  userIdentityModel: app.models.sentinel_identity,
  userCredentialModel: app.models.sentinel_credential
});
for (var s in config) {
  var c = config[s];
  c.session = c.session !== false;
  passportConfigurator.configureProvider(s, c);
}

require('../config/routes.js')(app);

app.start = function() {
  // start the web server
  return app.listen(function() {
    app.emit('started');
    var baseUrl = app.get('url').replace(/\/$/, '');
    console.log('Web server listening at: %s', baseUrl);
    if (app.get('loopback-component-explorer')) {
      var explorerPath = app.get('loopback-component-explorer').mountPath;
      console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
    }
  });
};

// start the server if `$ node server.js`
if (require.main === module) {
  app.start();
}
```
Please can someone give me a hand on this? I have over 2 months trying to figure this out and I'm about to quit using all of this.
regards.

**Comment by hackerunet** [comment]
any thoughts?? can someone give me a hint or a hand?? please...

**Comment by elropero** [comment]
Hey @hackerunet -- I went through a similarly frustrating process getting this component to behave as I liked. Like @julien-sarazin I forked the repo and customized it to do what I needed.

Could you create a public repo that demonstrates your specific issue? Would be easier for myself and/or others on this thread to debug. Also, the problem may make itself obvious if you try to create a trivial example that reproduces the issue.

**Comment by hackerunet** [comment]
Thanks a lot @elropero , about 1 hour ago I made everything work, I forgot to add in passport.js configuration cookies:true for example, after I finally realize that the options parameter is needed (conclusion I got checking out the passport configurator js file in node modules) I was able to get my user succesfully loged in and recognized by the API end point, but after that, I got a Roles resolver problem and I manage to solve it too, then I had an angular issue sending the X-Access-Token header and I solved it too and now, I'm good to go with the 97% of the rest of my project.
There are serious problems with loopback and basically all are product of lack of documentation, the api generator and the framework is great but the documentation is awfull and is really hard to get exactly what we need reading a document, there's a lot of time wasted in research and because of that, if a user don't know the framework, would be better and productive to change it's mind about using loopbak.
regards and thanks a lot... the community is the only great thing loopback has and it's very usefull.

**Comment by elropero** [comment]
I hear you @hackerunet. I know they have been working hard on 3.0, I hope as you do that some of the documentation gaps will be filled in. A lot of the docs are decent, and I don't think this passport module is indicative of the broader set. However, this module has caused a lot of head-scratching from those on this thread. Agree that without the community it would have been very difficult to get things up and running. Good luck!

**Comment by hackerunet** [comment]
Thank you andrew. Well, that's why is a great community, people like you
are really y worried about strongloop programmers. Thanks a lot.

**Comment by dakotahNorth** [comment]
@hackerunt ... that is awesome that you got it to work. So far I have been unsuccessful. Can you please provide details of what you did to get this working?

**Comment by dakotahNorth** [comment]
Following @hackerunet note above, I used @jamesjjk "loopback-component-passport": "git+https://github.com/jamesjjk/loopback-component-passport.git" and have been able to get it to work 90% of the way. The last remaining issue is that REST based calls for local logins don't authenticate. 

Facebook and Google (both logging in and REST based calls) work like a charm ... and local logins work except for when I login with a local user and use the access_token to make a REST base call.  

Any help would be greatly appreciated!

**Comment by hackerunet** [comment]
Well i don't have a very well documented procedure but i think everything
is up to configuration and the replace of the original loopback passport
component with the suggested repository forked. Let me get a procedure in
next days amd i'll post it. I have it working 100%

**Comment by dakotahNorth** [comment]
Note above about Facebook and Google both working like a charm ... they work if I force the cookies to be written not to be signed. So I forced signed to be false in the code below. Therefore, the token that is set can be used directly in the REST call. Otherwise ... I get authentication failed. 

     function addCookies(req, res, user_id, access_token, ttl) {
     res.cookie('access_token', access_token,
        {
          signed: req.signedCookies ? true : false,
          // maxAge is in ms
          maxAge: 1000 * ttl
        });
       res.cookie('userId', user_id.toString(), {
       signed: req.signedCookies ? true : false,
      maxAge: 1000 * ttl
    });

This issue goes into the ajax call that uses the token: https://github.com/strongloop/loopback-component-passport/issues/176

**Comment by dakotahNorth** [comment]
Hey ... @hackerunet, any chance to upload that configuration?

**Comment by hackerunet** [comment]
Yes. I've been sick and not be able to open up my laptop again, ill upload
it as sooners as i get better.

**Comment by dakotahNorth** [comment]
Feel better and thanks!

**Comment by hackerunet** [comment]
// Passport Configuration for Local provider

{
  "local": {
    "provider": "local",
    "module": "passport-local",
    "usernameField": "email",
    "passwordField": "password",
    "authPath": "/api/account/login",
    "successRedirect": "/private",
    "failureRedirect": "/login",
    "failureFlash": true,
    "setAccessToken": true,
    "session" : true,
    "callbackHTTPMethod": "post",
    "flashResponse":true,
    "cookie":true
  }

**Comment by dakotahNorth** [comment]
Awesome ... thanks! 

Cleared up all of the issues except for 1. 

Rest based calls. 

I discuss this over at #176. Basically, from the code below from [passport-configurator.js](https://github.com/jamesjjk/loopback-component-passport/blob/master/lib/passport-configurator.js), the cookies are being set as signed: 


     function addCookies(req, res, user_id, access_token, ttl) {
     res.cookie('access_token', access_token,
         {
           signed: req.signedCookies ? true : false,
           // maxAge is in ms
           maxAge: 1000 * ttl
         });
     res.cookie('userId', user_id.toString(), {
       signed: req.signedCookies ? true : false,
       maxAge: 1000 * ttl
     });
     }

But REST isn't expecting a signed call and therefore tells me that authorization failed. 

I set up tokens as such 

    app.middleware('session:before', loopback.cookieParser(app.get('cookieSecret'))); 
    app.middleware('session', loopback.session({
       secret: 'cookieSecret',
       saveUninitialized: true,
       resave: true,
     }));

**Comment by chkuendig** [comment]
Got it to work thanks to the branch of  @jamesjjk  - this is really something which needs to be fixed in mainline (or some easy explanation on how to access /api endpoints with the connect-sessions from passport)

**Comment by jdschreck** [comment]
I have the following related problem...  We have multiple services using passport authentication
with LDAP.  Some use loopback and others don't.  If a user logs into a loopback project they get 
both the session and the access token and things are good.  But if a user logs into a non-loopback
project first they obtain the passport session but not the access token.  Is there some way that
when the user then comes to a loopback server with a valid passport session that the access token can be created?

**Comment by jdschreck** [comment]
I have made some progress on this by using the code suggested above to use res.cookie, however,
it does not work for the immediate call but rather for the next call.  I am presuming that this is
because setting in on res does not take effect until that response goes back to the browser and the
browser sends the new signed cookie with the the next request.  Any ideas on how I can get this to take effect right away?

**Comment by bajtos** [comment]
@michaelfreund I don't think this is related to loopback-context. I skimmed through the comments above and my understanding is that local login/logout endpoints are not setting/clearing the authentication cookie correctly. The built-in User model (`/api/users/login`) does not set cookies, this is by current design. If there are different endpoints provided by loopback-component-passport and they are not setting the cookie correctly, then it is probably a bug in the way how these endpoints are implemented.

I am afraid my knowledge of this component is pretty minimal and therefore I don't know how to help you.

**Comment by michaelfreund** [comment]
@bajtos That is correct. I know that the built-in model does not support cookie handling. Remote methods are also difficult to get up and running. We have been working on a solution that allows you to define a custom callback for Local Auth without breaking existing applications. We will also send a separate pull request for the email verification problem using a custom email verification callback.

**Comment by michaelfreund** [comment]
@bajtos Pull request sent. We have also added two examples of how to use the callbacks.

- Enable custom callback for local auth strategy (Example https://gist.github.com/michaelfreund/edc147f1abefb39753496856306aa076)
- Enable custom callback for local auth email verification (Example https://gist.github.com/michaelfreund/412091675d36a04eb0dfdbb0c8d22ec6)

**Comment by michaelfreund** [comment]
#161

**Comment by ThatGuyFromFinland** [comment]
I think I have managed to find a solution, which does not require forking any node modules or adding shady hacks.

The problem here is, that 3rd party authentications will use callbacks, while in the LoopBack examples, the Passport local authentication is misimplemented.

The correct way to implement it, is to POST request to the "/auth/local/callback" directly, instead of POSTing to "/auth/local". "auth/local" will skip the defaultCallback, which does all the heavy lifting. The problem exists because ExpressJS redirects do not support HTTP 307 and passing credentials as query parameters would cause log files to become a security risk, even when using HTTPS.

You need to add these two lines to your "local" provider config:
```
"callbackHTTPMethod": "post",
"setAccessToken": true
```
And do the following change in your login form (for example, the file `server/pages/local.jade` in the example loopback passport project):
```
-      form(role='form', action='/auth/local', method='post')
+      form(role='form', action='/auth/local/callback', method='post')
```

I have posted full details here:
https://github.com/strongloop/loopback-example-passport/issues/99

**Comment by ataft** [comment]
Would love to see @jamesjjk fork integrated in. In addition to this issue, it also adds/fixes customCallback to the local login, which is needed.
```
if (authType === 'local' || authType === 'ldap'){
    var authCallback = options.customCallback || defaultCallback;
    self.app.post(authPath, authCallback)

```
